### ISSUE TITLE
Why do you think CM never asks questions?

### ISSUE THREAD

**Issue by theresaanna** [khandelwal/AskShashank#16]
Are you giving @cmc333333333333333 or whatever his username is wisdom on a channel we can't share in? What gives?

**Comment by khandelwal** [comment]
On AskShashank, we don't often ask others to help out with the answers, as we're very opinionated. However, I think this is a question for @cmc333333. I too, am very worried how he goes through life without advice from AskShashank.

**Comment by cmc333333** [comment]
Github's tagline used to be "Social Coding", but they got rid of that because ew, you know? I don't know about you, but I certainly don't want "likes" in my source tree, DMs in my documentation, or Google pluses in my markdown. I like my code and society as I like my peanut butter and jelly - completely separated and almost exclusively the former.

Besides, Shashank and I see each others' thoughts. Why do you think I'm so afraid of him?
