### ISSUE TITLE
Separation anxiety

### ISSUE THREAD

**Issue by stephanieosan** [khandelwal/AskShashank#2]
One of my team members whom I love dearly is leaving. 

Who will encourage me to eat chocolate? Who will tell me that I ran a good meeting? Who will I complain to until things feel manageable? Who will help me be a better designer? HOW WILL I GO ON WITHOUT HER DON'T LEAVE I CAN'T TAKE ITTTTTTTT

So, what do I do?

**Comment by khandelwal** [comment]
I think the heart of the matter here is your relationship with your team member. It's clear you think your relationship is a strong, useful one. One where you couldn't think of parting ways. That the two of you would keep designing together while the sun set over the zombie ridden post-apocalyptic future. 

I'll be the one to break it to you (tough love). I don't think your team member thinks the same way. I'm sorry. Otherwise, why would she leave?

Your depression will pass. Remember your first boyfriend, and how you thought he was the love of your life and YOUR RELATIONSHIP WOULD NEVER END. Well, it did - and you eventually got over it (if you didn't we'll need to talk more). 

This too shall pass. 

I suggest you start visiting the designer equivalent of bars, and seek out a new partner. There's plenty more designers in the technicolor ocean. Even one who'll do all the things you miss, and still stay loyal.

Chocolate is easy to buy. Loyalty less so.
