### ISSUE TITLE
Fancy Meetings

### ISSUE THREAD

**Issue by rjmajma** [khandelwal/AskShashank#27]
Dear Shashank,

I have a friend. His name is Schmaphael. He has a problem. He was going to take his colleagues with him to a fancy-pants meeting, but then was told there was no room. 

He feels awful about this.

How can Schmaphael make this up to his colleagues and friends?

Your pal,

Not Schmaphael

**Comment by jehlers** [comment]
:cookie: :cookie: :cookie: :cookie: :cookie: :cookie:

**Comment by khandelwal** [comment]
You know, it's really strange. But just this week, a friend of mine at the office was going to take me to a meeting with a Very Important Person in a place, that, let's just say is where a Very Very Important Person works. But I was cancelled from that meeting. So, I know how you feel. My friend must feel the same. I will attempt to answer your question the best I can (it's hard being in the rejected position). 

We're just going to get rid of the Schmaphael fellow huh? It's you, isn't it? I've figured it out. 

You must be new to leadership, not used to being in charge are you? This scenario is great, because we can turn your guilt into a teaching moment. Here's the deal. You're in charge. You get to decide things without have to explain yourself. You want someone in the meeting? Tell them. You want to remove someone from the meeting? Tell them it's cancelled. You might want to give them enough time to return that suit they just bought though. Once it's altered, you can't return it. Sometimes people don't have places they can wear a suit to. But that's just if you're nice, you know? Otherwise be a leader. Be the person in charge. "I put you in this meeting, I'll take you out".

**Comment by rjmajma** [comment]
Well. 

That was not the real talk I expected. Thank you.
