### ISSUE TITLE
What are you ALL making for Thanksgiving?

### ISSUE THREAD

**Issue by iuloshi** [khandelwal/AskShashank#28]
It's my favorite food holiday, and I'd love some new ideas for dishes. Are there any Shashank classics?

**Comment by theresaanna** [comment]
Hi @iuloshi! Why you never on IM anymore?

**Comment by iuloshi** [comment]
@theresaanna No Gmail access at work. :( I miss you guys!

**Comment by rjmajma** [comment]
I will be making the gravy and macaroni and cheese. They will both be delicious.

**Comment by stephanieosan** [comment]
Waaaaa? No gmail is crazy-talk.

I have a killer pecan pie recipe I always make. Back in the Texas days, we had pecan trees in our backyard, and harvest is in early fall, so we'd have homegrown homemade pecan pie. Now that's less feasible.

**Comment by rjmajma** [comment]
You should share your recipe, @stephanieosan. 

My grandparents have a pecan tree at home as well. I already miss El Paso.

**Comment by khandelwal** [comment]
@stephanieosan What is the Colorado equivalent of Pecan Pie?

**Comment by khandelwal** [comment]
Also, are you still an Osan?

**Comment by stephanieosan** [comment]
<<< Osan 4 lyfe!

I don't know what the Colorado equivalent of pecan pie is. Maybe I need to find out next week! Since we've moved here, we've only had Thanksgiving with James' parents, who are also originally Texans. 

##### Stephanie's magical pecan pie recipe

1 Homemade crust (see endnote)
6 Tbsp unsalted butter
1 c packed brown sugar
1/2 tsp salt
3 lg eggs
3/4 c light corn syrup
2 c pecans, toasted and chopped—this is crucial: toast them in a skillet until they're deep brown and smell heavenly, then if you have whole pecans, chop them into small pieces once cooled. Don't use whole pecans! You will have a sad pecan pie!
1. Preheat oven to 375, blind bake crust for 15-20 minutes.
2. Melt butter in a heat safe medium bowl that is sitting in a skillet of simmering water. Remove butter bowl from skillet, mix in sugar and salt until dissolved. Beat in eggs (do this quick, so they don't become scrambled eggs), then corn syrup and vanilla. Return bowl to hot water, stir until the mixture is shiny and hot, about 130 degrees, but I always just eyeball it. Remove from heat, stir in chopped pecans.
3. As soon as pie shell comes out of the oven, reduce temp to 275. Pour pecan mixture into pie shell.
4. Bake 50 to 60 minutes. Center should still be soft when pressed. Pie should cool completely, about 4 hours, before serving. I like to serve it with fresh whipped cream that just barely has any sugar in it and is spiked with bourbon.

##### End note / What is a pie without a homemade crust?

This is the crust recipe I'm into these days:
1.25 cups all purpose flour
0.5 tsp salt
10 Tbsp unsalted butter, chilled, cut into small chunks
4 Tbsp vodka straight from the freezer
2-4 Tbsp ice water

Mix dry ingredients together. Add butter. A food processor makes blending in the butter super simple, but if you don't have one, a pastry cutter or a few butter knives held in each hand will work just fine. You want to get the consistency to be somewhere between pea sized and cornmeal sized. If you're in a food processor, now is the time to shift the mixture to a bowl.

Add the vodka (you can just use more ice water if you don't have any on hand) and ice water and stir with a spoon/your hands until it comes together in a ball. Add a little more water if needed, but it should be on the drier side. Mush the ball into a disk, cover in plastic wrap, and set in the fridge for at least 30 minutes. But, you can totally do this a day or two before if you want.

When the dough is chilled, bring it out, roll it out on a floured surface, you want it to be an inch or two larger in diameter than your pie plate so that you can shape up nicely. Ta-da! Pie crust!

**Comment by rjmajma** [comment]
:fork_and_knife: 

That sounds amazing.

**Comment by iuloshi** [comment]
THANK YOU FOR SHARING YOUR RECIPE @stephanieosan!!! OMG ALL OF THE PIES MY FAVORITE THING AHHHH!! I'm going to convince my sister to add that to the menu this year. :) Are you celebrating Thanksgiving with James' family again or heading back to TX?

**Comment by iuloshi** [comment]
Also @rjmajma: mac and cheese should definitely be a Thanksgiving staple. I don't know why that hadn't occurred to me before. #genius

**Comment by jehlers** [comment]
There is a lack of :thanksgiving: emoji to add to this thread :disappointed:

**Comment by khandelwal** [comment]
What do the Ehlers have for Thanksgiving?

**Comment by jehlers** [comment]
Nothing out of the ordinary - Turkey, Green Bean Casserole.. we may have had some Kugel last year!

**Comment by mebates** [comment]
Wah, so many good sides! I want to make so many but need to make some choices:
- roasted brussel sprouts with bacon
- green bean casserole
- peas with pearl onions (this is my family's thing?)
- squash something
- mashed potatoes obviously
- creamed corn

How many are two many for only four people!? I'm hosting at my house this year. And planning to make this [chocolate pecan pie](http://cooking.nytimes.com/recipes/6413-chocolate-pecan-pie) but may merge it with @stephanieosan's recipe.

**Comment by stephanieosan** [comment]
Sides are my favorite thing, so I'm biased, but maybe 3-4? Also depends on whether your fellow diners are bringing anything.

Squash idea: I haven't had time to recreate this into a real recipe yet, but I had this dish at a restaurant and it was divine and didn't seem hard to make at home: roasted delicata squash sliced in 1/2" semicircles, tossed in probably a little olive, salt, pepper, laid out in a pan, drizzle with balsamic and crumbled blue cheese.

**Comment by iuloshi** [comment]
My Mom makes this mallow mash, which basically has an oatmeal crust, layers of cranberry sauce and sweet potato mash, and toasted baby marshmellows on top. I look forward to it every year.

Also not gonna lie, but I like Stove Top stuffing. Kind of a lot. 

And then there's [this](http://gothamist.com/2014/11/17/thanksgiving_ramen.php).

**Comment by rjmajma** [comment]
...wut? 

That looks amazing.

**Comment by ascott1** [comment]
I think gravy and stuffing are my favoritest things about Thanksgiving. A few years ago I started making my own stock for the gravy and that dramatically improved both my gravy and stuffing (I can't bring myself to use the word dressing) recipes.

My stock recipe is some amalgamation of [these](http://www.epicurious.com/recipes/food/views/Brown-Turkey-Stock-231026) [two](http://www.epicurious.com/recipes/food/views/Homemade-Turkey-Stock-240445), but I usually use chicken wings and thighs since they're cheap and easy to get a few days before Thanksgiving.  

For stuffing, I typically make some sort of sage stuffing. Sometimes I make a second stuffing dish with sausage and little chunks of apples as well.

**Comment by ascott1** [comment]
Oh, and I find it interesting that no one has brought up Turkey. I'm a serious devotee of brining the bird.
