### ISSUE TITLE
Why does my cat like going in the fridge?

### ISSUE THREAD

**Issue by theresaanna** [khandelwal/AskShashank#6]
Its not like its hot here, at all. Also, the shelf he goes on, there's nothing but Diet Coke. He eats a lot of weird things, but he has no interest in Diet Coke.

He gets excited whenever he thinks you're going into the kitchen to open the fridge and queues up to sneak in like a little furry eel. When he goes in, he just sits there. If you close the door, he continues to just sit there contentedly.

Once, long ago, we humored our other cat by letting her stay in the fridge awhile. But then we forgot she was in there. We nearly had a popsicle cat.

**Comment by iuloshi** [comment]
How long was your cat in the fridge?!

**Comment by theresaanna** [comment]
Not sure. Maybe 15-20 minutes? This was Dora. Now we don't close the door if there's a cat in the fridge, so it leads to a lot of exasperated sighing, pleading, and trying to push the cat out without getting mauled.

**Comment by fna** [comment]
Maybe your cat is one of those youtube cats that love boxes.

**Comment by khandelwal** [comment]
Dear @theresaanna, 

There are a couple things here that have me worried. 

The first is that there appears to be a lack of food in your home. There's an entire shelf in your fridge with nothing but Diet Coke? This is not healthy. Berkeley has several farmers' markets where you can buy delicious, fresh produce. Here is one that happens on Saturdays: http://ecologycenter.org/fm/. Of course, since it is Berkeley it can't just be called a farmers' market. It has to be the _ecology center_.  I don't even know what that means. We just have normal markets here. They do, however, appear to have fresh vegetables. Maybe that's what your cat is trying to tell you. Like a 'this empty shelf is ridiculous' type message. 

The second is that the cats seem to be ruling your life. Allowing your cat to stay in the fridge? That's just giving in to the Cat Overlords. That's what the cat wants. We should always remember to maintain Human Superiority. I don't want to wake up one day to realize that your Cat has taken over California because you gave it a false sense of leadership by allowing it to stay in the Fridge. It's a Cat. It should not be in the Fridge. You would not normally allow a cat to be in the Fridge. DON'T LET THE CATERRORISTS WIN. 

I look forward to seeing a picture of your fridge filled with food. 

Love, 
@khandelwal

P.S. Here are some other pictures of cats in fridges http://www.buzzfeed.com/samimain/26-cool-cats-who-live-in-fridges-5pfv. What this tells you is that this is a CO-ORDINATED EFFORT by the CATS. DON'T LET THEM WIN.

**Comment by theresaanna** [comment]
Um, hello, this is Berkeley. We partake in communal meals with food from the urban farm on the next block. Look here: http://urbanadamah.org/. You see that goat on the top left? We get milk and cheese from that exact goat. Its our neighbor - on the same block as the urban farm. Though this place has a farm, too. You wouldn't believe the size of the radishes they grow.

When we do stoop to going to a grocery store, all of the food is organic and preservative-free. Meaning we need to eat it immediately when we get home or else it will go bad. And if you let anything go to waste, there's a neighborhood wall of shame where you need to come up with some manner of artistic rendering of the item and write a poem expressing your shame/guilt/gratitude. You wouldn't believe how judgey these people get. I mean, we don't own a Prius or electric car, so we don't really have room for mistakes.

And yes, I have a Diet Coke problem. Please don't tell the people here. We sneak it in late at night from a Walgreens in Oakland while everyone is distracted by the live Jewish worship music at the community center.
